### ISSUE TITLE
Fallback isn't functional

### ISSUE THREAD

**Issue by virtualstep** [caffeinated-docs/themes#1]
Good evening,

the fallback mode is not functional.

I've created the folders within the public folder and change from Laravel view function to Theme::view.

In using path "use Caffeinated\Themes\Facades\Theme";

After reload of my page I have white, blank page without an error.

Is here a problem ?

**Comment by kaidesu** [comment]
You must register the facade from within your `config/app.php` file - not through the `use` method.

http://codex.caffeinated.ninja/themes/master/installation

**Comment by virtualstep** [comment]
in app config the facade is registred

without using I have the error theme controller Not found



Am 29. Januar 2015 23:13:12 schrieb Shea Lewis <notifications@github.com>:

**Comment by kaidesu** [comment]
Right - because everything is namespaced within Laravel. If you call `Theme::view`, it is going to look within the *current* namespace, which would be `App\Http\Controllers`.

Because facades are registered at the root of the namespace, you must either use `\Theme::view()` or you can use `use Theme;` from within your controller.
